version: '3.8'

services:
  todoapi:
    build: .
    container_name: todo_app
    ports:
      - "8000:8000"  # Expose for debugging, optional if only using nginx
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - todoapi
    restart: unless-stopped
